# Usar um servidor web super leve
FROM nginx:stable-alpine

# Copiar apenas a pasta 'dist' (o site pronto) para dentro do servidor
COPY dist /usr/share/nginx/html

# Expor a porta 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
