FROM nginx:stable-alpine
# Copia a sua pasta dist
COPY dist /usr/share/nginx/html
# Copia a configuração que acabamos de criar
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]