server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Adicione este bloco para garantir que o CSS e JS carreguem
    location /assets/ {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types;
    }
}