server {
    listen 80;
    
    # Pasta onde o site real está localizado
    root /usr/share/nginx/html;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Esta é a parte que falta para carregar o seu layout
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}