services:
  backend:
    build: ./backend
    container_name: dashboard-backend
    restart: always
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: dashboard-frontend
    restart: always
    ports:
      - "80:80" # Mapeia a porta 80 da VPS para a 80 do Nginx
